import { createSlice, /* createAsyncThunk */ } from '@reduxjs/toolkit';

const roofTopSlice = createSlice({
  name: 'roofTopSlice',
  initialState: {
    rooInspectionData: {
      inspectionNo: '',
      inspectionDate: '',
      firstName: '',
      lastName: '',
      areaCode: '',
      phoneNumber: '',
      email: '',
      address: '',
      address_1: '',
      city: '',
      state: '',
      postalCode: '',
      damageStatus: '',
      debrisNotes: '',
      drainageNotes: '',
      deformation: '',
      coating: '',
      granular: '',
      punctures: '',
      cracks: '',
      blister: '',
      atticCondition: '',
      missingTabs: '',
      corrosion: '',
      edges: '',
      gutter: '',
      chimney: '',
      ceilingDamage: '',
      ceilingDebris: '',
      ceilingDrainage: '',
      exteriorWallWaterLeaks: '',
      exteriorWallCrack: '',
      exteriorWallStain: '',
      interiorWallWindowAligned: '',
      interiorWallCracks: '',
      interiorWallStain: '',
      comment: '',
      inspectorFirstName:'',
      inspectorLastName:'',
      inspectorPosition:'',
      inspectorAreaCode:'',
      inspectorPhoneNo:'',
      inspectorEmail:'',
      // inspectorInspectionDate:'',
      damageDropDown:'',
      debrisDropDown:'',
      damageConditionDropDown:'',
      debrisConditionDropDown:'',
      drainageDropDown:'',
      drainageDropDownCondition:'',
      deformationDropDown:'',
      deformationConditionDropDown:'',
      coatingDropDown:'',
      coatingConditionDropDown:'',
      granularLossDropDown:'',
      granularLossConditionDropDown:'',
      puncturesDropDown:'',
      puncturesConditionDropDown:'',
      cracksDropDown:'',
      cracksConditionDropDown:'',
      blisterDropDown:'',
      blisterConditionDropDown:'',
      atticDropDown:'',
      atticConditionDropDown:'',
      missingtabsDropDown:'',
      missingtabsConditionDropDown:'',
      metalcorrosionDropDown:'',
      metalcorrosionConditionDropDown:'',
      defromedEdgesDropDown:'',
      defromedEdgesConditionDropDown:'',
      gutterDropDown:'',
      gutterConditionDropDown:'',
      ventsDropDown:'',
      ventsConditionDropDown:'',
      waterleaksDropDown:'',
      waterleaksConditionDropDown:'',
      ceilingcracksDropDown:'',
      ceilingcracksDropDownConditionDropDown:'',
      ceilingWaterStainDropDown:'',
      ceilingWaterStainConditionDropDown:'',
      exteriorWallWaterLeaksDropDown:'',
      exteriorWallWaterLeaksConditionDropDown:'',
      ExteriorWallcracksDropDown:'',
      ExteriorWallcracksConditionDropDown:'',
      ExteriorWallStainDropDown:'',
      ExteriorWallStainConditionDropDown:'',
      interiorWallwindowalignedDropDown:'',
      interiorWallwindowalignedConditionDropDown:'',
      interiorWallcracksDropDown:'',
      interiorWallcracksConditionDropDown:'',
       interiorWallStainDropDown:'',
       interiorWallStainConditionDropDown:'',
    },
    formData: {},
    checkListForm: {},
    customFormData: {},
    userId: '',
    gradesMapping: {}
  },
  reducers: {
    SetRoofTopState(state, { payload: { field, value } }) {
      state[field] = value;
    }
  },
  extraReducers: {
  }
});

const { reducer, actions } = roofTopSlice;

export const {
  SetRoofTopState
} = actions;

export default reducer;
